### Send POST to create Ticket
POST http://localhost:8080/genielog/ticket/create 
Content-Type: text/plain

{"token":"96b29b22-cefb-4699-93b9-9fcc97aa003e","ticket":{"adresse":{"codePostal":"69000","numero":32,"rue":"RUE ALAINE","ville":"LYON"},"categorie":"Etude","competences":[],"demandeur":{"id":12,"nom":"RENARD","prenom":"Maxime"},"objet":"TEST","statut":"Resolu","technicien":{"id":2,"nom":"VITTONE","prenom":"Jules"},"type":"Demande","priorite":1}} 
###

### Send POST to create Ticket
POST http://localhost:8080/genielog/ticket/create 
Content-Type: text/plain

{"token":"96b29b22-cefb-4699-93b9-9fcc97aa003e","ticket":{"adresse":{"codePostal":"75000","numero":29,"rue":"Rue truc","ville":"Paris"},"categorie":"Etude","competences":[],"demandeur":{"id":18,"nom":"Maua","prenom":"momo"},"objet":"Champi","statut":"Ouvert","technicien":{"id":5,"nom":"dedeq","prenom":"sjdf"},"type":"Incident","priorite":3}} 
###


