POST http://localhost:8080/GenieLogiciel_war_exploded/ticket/modify
Content-Type: text/plain

{
  "token": "96b29b22-cefb-4699-93b9-9fcc97aa003e",
   "clientId":123456789,
   "ticket":{
      "categorie":"Temperature",
      "competences":[
         "Electricien",
         "Frigoriste"
      ],
      "priorite":1,
      "demandeur":{
         "id":1,
         "nom":"ALIMI",
         "prenom":"Jean"
      },
      "description":"Bonjour,\n\n Notre meuble vitrine réfrigérée qui nous sert à la présentation des charcuteries n'est plus assez froid, il est impossible de descendre au-delà de 6°.\n ",
      "nomClient":"A",
      "objet":"La vitrine réfrigérée n'est plus assez chaude",
      "statut":"En cours",
      "technicien":{
         "id":6,
         "nom":"SHEIKH",
         "prenom":"MUHAMMAD"
      },
      "type":"Incident",
      "adresse":{
         "numero":32,
         "rue":"RUE ALAINE",
         "ville":"LYON",
         "codePostal":"69000"
      },
      "id":5
   }
}
###
### Send POST create Task
POST http://localhost:8080/genielog/tache/create
Content-Type: text/plain

{"token":"96b29b22-cefb-4699-93b9-9fcc97aa003e","tache":{"statut":"En cours","objet":"TEST","description":"","ticketParent":8,"tempsPasse":-1,"id":-1,"pourcentage":0,"tempsEstime":40,"competences":[],"technicien":{"nom":"VITTONE","prenom":"Jules","id":2}}}
###

### Create Client with Demandeurs
POST http://localhost:8080/genielog/client/create
Content-Type: text/plain

{
  "token": "96b29b22-cefb-4699-93b9-9fcc97aa003e",
  "client": {
    "SIREN": 992223,
    "nom": "QSDQSD",
    "adresse": {
      "numero": 1,
      "rue": "BOQSDSQD",
      "ville": "OKOKQSD",
      "codePostal": "23323"
    },
    "demandeurs": [
      {
        "SIRET": 82323,
        "demandeur": {
          "nom": "SQDSD",
          "prenom": "QSDSDQ",
          "sexe": "M"
        },
        "telephone": "0012",
        "idAdresse": 35
      }
    ]
  }
}
###
##Create User
POST http://localhost:8080/genielog/user/create
Content-Type: text/plain

{
  "staff": {
    "staffSexe": "M",
    "staffUserName": "BORDE000LUSER",
    "staffPassword": "1234",
    "staffMail": "BORDELUSER@BORDELUSER.com",
    "staffAdress": {
      "numero": 230,
      "rue": "BORDELUSER",
      "ville": "BORDELUSER",
      "codePostal": "2323"
    },
    "staffSurname": "BORDELUSER",
    "staffName": "BORDELUSER",
    "staffTel": "3444",
    "staffCompetency": [],
    "staffRole": [
      "RespTech"
    ]
  },
  "token": "96b29b22-cefb-4699-93b9-9fcc97aa003e"
}
###

##Create User

POST http://localhost:8080/genielog/user/create
Content-Type: text/plain

{"token":"9b15a375-94e6-4de5-8fc6-a21ccf93a2aa",
"staff":{
"staffSexe":"M",
"staffUserName":"log000",
"staffPassword":"1234",
"staffMail":"sgvfsgdfdfsdfd",
"staffAdress":{"numero":1556,"rue":"dbfwbw","ville":"vfw<ddfv","codePostal":"vdwfvdwv"},
"staffSurname":"dfbgdwfbwdbwdfb",
"staffName":"jigbqfdigjubdnvuig",
"staffTel":"06452415",
"staffCompetency":[],
"staffRole":["Operateur"]}}
###