### Send POST to change clientName to clientId
POST http://localhost:8080/genielog/client/getId
Content-Type: text/plain

{"clientName":"Pops1920","token":"96b29b22-cefb-4699-93b9-9fcc97aa003e"}
###
### Liste Client
POST http://localhost:8080/genielog/client/list
Content-Type: text/plain

{"token":"96b29b22-cefb-4699-93b9-9fcc97aa003e"}

###
### Create Client without Demandeurs
POST http://localhost:8080/genielog/client/create
Content-Type: text/plain

{"token":"96b29b22-cefb-4699-93b9-9fcc97aa003e","client":{"SIREN":21,"nom":"tst","adresse":{"numero":500,"rue":"rue des saucissons","ville":"Jambon","codePostal":"25811"}}}
###
### Create Client with Demandeurs
POST http://localhost:8080/genielog/client/create
Content-Type: text/plain

{"token":"96b29b22-cefb-4699-93b9-9fcc97aa003e","client":{"SIREN":21,"nom":"tst","adresse":{"numero":500,"rue":"rue des saucissons","ville":"Jambon","codePostal":"25811"},
"demandeurs":[{"SIRET":12345678912349, "idAdresse":12, "demandeur":{"nom":"essaie","prenom":"je suis","sexe":"M"}, "telephone":"0645789878"}]}}
###

### Modify Client without Demandeur
POST http://localhost:8080/genielog/client/modify
Content-Type: text/plain

{"token":"96b29b22-cefb-4699-93b9-9fcc97aa003e","client":{"SIREN":21,"nom":"testouille","adresse":{"numero":258,"rue":"rue des frotages","ville":"Saint Nectaire","codePostal":"25811"}}}
###
### Modify Client with Demandeur
POST http://localhost:8080/genielog/client/modify
Content-Type: text/plain

{"token":"96b29b22-cefb-4699-93b9-9fcc97aa003e","client":{"SIREN":21,"nom":"testouille","adresse":{"numero":258,"rue":"rue des frotages","ville":"Saint Nectaire","codePostal":"25811"},
"demandeurs":[{"SIRET":12345678912310, "idAdresse":12, "demandeur":{"nom":"essaie","prenom":"je suis","sexe":"M","id":14}, "telephone":"0645789879"}]}}
###

### Modify Client with Demandeur empty
POST http://localhost:8080/genielog/client/modify
Content-Type: text/plain

{"token":"96b29b22-cefb-4699-93b9-9fcc97aa003e","client":{"SIREN":21,"nom":"testouille","adresse":{"numero":258,"rue":"rue des frotages","ville":"Saint Nectaire","codePostal":"25811"},
"demandeurs":[]}}
###

### Init Client
POST http://localhost:8080/genielog/client/init
Content-Type: text/plain

{"token":"96b29b22-cefb-4699-93b9-9fcc97aa003e","SIREN":123456789}

###
### Delete Client
POST http://localhost:8080/genielog/client/delete
Content-Type: text/plain

{"token":"96b29b22-cefb-4699-93b9-9fcc97aa003e","SIREN":21}

###