POST http://localhost:8080/GenieLogiciel_war_exploded/ticket/modify
Content-Type: text/plain

{
  "token": "96b29b22-cefb-4699-93b9-9fcc97aa003e",
   "clientId":123456789,
   "ticket":{
      "categorie":"Temperature",
      "competences":[
         "Electricien",
         "Frigoriste"
      ],
      "priorite":1,
      "demandeur":{
         "id":1,
         "nom":"ALIMI",
         "prenom":"Jean"
      },
      "description":"Bonjour,\n\n Notre meuble vitrine réfrigérée qui nous sert à la présentation des charcuteries n'est plus assez froid, il est impossible de descendre au-delà de 6°.\n ",
      "nomClient":"A",
      "objet":"La vitrine réfrigérée n'est plus assez chaude",
      "statut":"En cours",
      "technicien":{
         "id":6,
         "nom":"SHEIKH",
         "prenom":"MUHAMMAD"
      },
      "type":"Incident",
      "adresse":{
         "numero":32,
         "rue":"RUE ALAINE",
         "ville":"LYON",
         "codePostal":"69000"
      },
      "id":5
   }
}
###
### Send POST create Task
POST http://localhost:8080/genielog/tache/create
Content-Type: text/plain

{"token":"96b29b22-cefb-4699-93b9-9fcc97aa003e","tache":{"statut":"En cours","objet":"TEST","description":"","ticketParent":8,"tempsPasse":-1,"id":-1,"pourcentage":0,"tempsEstime":40,"competences":[],"technicien":{"nom":"VITTONE","prenom":"Jules","id":2}}}
###

### Create Client with Demandeurs
POST http://localhost:8080/genielog/client/create
Content-Type: text/plain

{
  "token": "96b29b22-cefb-4699-93b9-9fcc97aa003e",
  "client": {
  "SIREN": 9280312,
  "nom": "HUR0LE",
  "adresse": {
    "numero": 01,
    "rue": "HURL00000EADRE",
    "ville": "HURLVIL",
    "codePostal": "9933"
  },
  "demandeurs": [
    {
      "SIRET": 92323,
      "demandeur": {
        "nom": "NOM",
        "prenom": "PRENOM",
        "sexe": "M",
        "id": 17
      },
      "telephone": "011251454",
      "idAdresse": 27
    },
    {
      "SIRET": 2323,
      "demandeur": {
        "nom": "QDQSd",
        "prenom": "qSDd",
        "sexe": "M"
      },
      "telephone": "323",
      "idAdresse": 60
    }
  ]
}
}
###
##Create User
POST http://localhost:8080/genielog/user/create
Content-Type: text/plain

{
  "staff": {
    "staffSexe": "M",
    "staffUserName": "BORDE000LUSER",
    "staffPassword": "1234",
    "staffMail": "BORDELUSER@BORDELUSER.com",
    "staffAdress": {
      "numero": 230,
      "rue": "BORDELUSER",
      "ville": "BORDELUSER",
      "codePostal": "2323"
    },
    "staffSurname": "BORDELUSER",
    "staffName": "BORDELUSER",
    "staffTel": "3444",
    "staffCompetency": [],
    "staffRole": [
      "RespTech"
    ]
  },
  "token": "96b29b22-cefb-4699-93b9-9fcc97aa003e"
}
###

##Create ticket

POST http://localhost:8080/genielog/ticket/create
Content-Type: text/plain

{
  "token": "96b29b22-cefb-4699-93b9-9fcc97aa003e",
  "ticket": {
    "categorie": "Etude",
    "competences": [
      "Electricien",
      "Frigoriste"
    ],
    "priorite": 1,
    "demandeur": {
      "sexe": "M",
      "id": 32,
      "nom": "sdqs",
      "prenom": "dqsdq"
    },
    "description": "Descripto",
    "nomClient": "A",
    "objet": "Objecto",
    "statut": "Bloque",
    "technicien": {
      "sexe": "M",
      "id": 1,
      "nom": "CLAUDE",
      "prenom": "Philippe"
    },
    "type": "Demande",
    "adresse": {
      "numero": 23,
      "rue": "232 2323",
      "codePostal": "qsds"
    }
  }
}
###

##Create ticket

POST http://localhost:8080/genielog/ticket/create
Content-Type: text/plain

{
  "token": "96b29b22-cefb-4699-93b9-9fcc97aa003e",
  "ticket": {
    "categorie": "Etude",
    "competences": [
      "Electricien",
      "Frigoriste"
    ],
    "priorite": 1,
    "demandeur": {
      "sexe": "M",
      "id": 33,
      "nom": "qsdqsd",
      "prenom": "qsdqsd"
    },
    "description": "sqdsqdsqd",
    "nomClient": "A",
    "objet": "OBjecto",
    "statut": "Bloque",
    "technicien": {
      "sexe": "M",
      "id": 56,
      "nom": "CLAUDE",
      "prenom": "Philippe"
    },
    "type": "Demande",
    "adresse": {
      "numero": 23,
      "rue": "qsdqsd 3434",
      "codePostal": "kqsjdqs"
    },
    "taches": [
      {
        "statut": "En cours",
        "objet": "sdqsd",
        "description": "qsdqsd",
        "technicien": {
          "sexe": "M",
          "id": 65,
          "nom": "CLAUDE",
          "prenom": "Philippe"
        },
        "competences": [
          "Electricien"
        ],
        "tempsEstime": 56,
        "tempsPasse": 0
      },
      {
        "statut": "Ouvert",
        "objet": "qsdq",
        "description": "dsqd",
        "technicien": {
          "sexe": "M",
          "id": 63,
          "nom": "Irteza",
          "prenom": "She"
        },
        "competences": [
          "Mecanicien"
        ],
        "tempsEstime": 455,
        "tempsPasse": 0
      }
    ]
  }
}

###
##Modify ticket

POST http://localhost:8080/genielog/ticket/modify
Content-Type: text/plain

{
  "token": "96b29b22-cefb-4699-93b9-9fcc97aa003e",
  "clientId": 123456789,
  "ticket": {
    "categorie": "Temperature",
    "competences": [
      "Electricien",
      "Frigoriste"
    ],
    "priorite": 1,
    "demandeur": {
      "sexe": "M",
      "id": 12,
      "nom": "RENARD",
      "prenom": "Maxime"
    },
    "description": "Bonjour,\n Notre meuble vitrine réfrigérée qui nous sert à la présentation des charcuteries n'est plus assez froid, il est impossible de descendre au-delà de 6°.\n ",
    "nomClient": "A",
    "objet": "La vitrine réfrigérée n'est plus assez chaude",
    "statut": "En cours",
    "technicien": {
      "sexe": "M",
      "id": 2,
      "nom": "VITTONE",
      "prenom": "Jules"
    },
    "type": "Incident",
    "adresse": {
      "numero": 32,
      "rue": "RUE ALAINE",
      "ville": "LYON",
      "codePostal": "69000"
    },
    "taches": [
      {
        "statut": "En cours",
        "objet": "Chauffer le sol",
        "description": "sol le chauffer",
        "technicien": {
          "sexe": "M",
          "id": 66,
          "nom": "TAKITAKI",
          "prenom": "TAKITAKI"
        },
        "competences": [
          "Frigoriste"
        ],
        "tempsEstime": 23,
        "tempsPasse": 0
      }
    ],
    "id": 20
  }
}

###