### Send POST to get init info for Ticket
POST http://localhost:8080/genielog/ticket/init
Accept: */*
Cache-Control: no-cache
Content-Type: text/plain

{"clientId":"123456789","token":"96b29b22-cefb-4699-93b9-9fcc97aa003e"}
###
### Send POST to create Ticket without task
POST http://localhost:8080/genielog/ticket/create
Content-Type: text/plain

{"token":"96b29b22-cefb-4699-93b9-9fcc97aa003e","ticket":{"adresse":{"codePostal":"69000","numero":32,"rue":"RUE ALAINE","ville":"LYON"},"categorie":"Etude","competences":[],"demandeur":{"id":12,"nom":"RENARD","prenom":"Maxime"},"objet":"TESTEST","statut":"Resolu","technicien":{"id":2,"nom":"VITTONE","prenom":"Jules"},"type":"Demande","priorite":1}}
###
### Send POST to create Ticket with task
POST http://localhost:8080/genielog/ticket/create
Content-Type: text/plain

{"token":"96b29b22-cefb-4699-93b9-9fcc97aa003e","ticket":{"adresse":{"codePostal":"69000","numero":32,"rue":"RUE ALAINE","ville":"LYON"},"categorie":"Etude","competences":[],"demandeur":{"id":1,"nom":"ALIMI","prenom":"Jean"},"objet":"TESTEST","statut":"En cours","technicien":{"id":6,"nom":"SHEIKH MUHAMMAD","prenom":"Irteza"},"type":"Demande","priorite":1,
"taches":[{"statut":"En cours", "objet":"TEST", "competences":[], "technicien":{"id":2,"nom":"VITTONE","prenom":"Jules"}, "tempsEstime":40}]}}
###

### Send POST to modify Ticket without task
POST http://localhost:8080/genielog/ticket/modify
Content-Type: text/plain

{"clientId":123456789,"token":"96b29b22-cefb-4699-93b9-9fcc97aa003e","ticket":{"adresse":{"codePostal":"69000","numero":32,"rue":"RUE ALAINE","ville":"LYON"},"categorie":"Temperature","competences":["Electricien", "Frigoriste"],"demandeur":{"id": 12,"nom":"RENARD","prenom":"Maxime"},"objet":"La vitrine réfrigérée n'est plus assez froide","description":"Bonjour,

 Notre meuble vitrine réfrigérée qui nous sert à la présentation des charcuteries n'est plus assez froid, il est impossible de descendre au-delà de 6°.
 ","statut":"En cours","technicien":{"id":9,"nom":"LESTOIL","prenom":"Veronique"},"type":"Incident","id":8,"priorite":2}}
###
##Send POST to modify the state
POST http://localhost:8080/genielog/ticket/state
Content-Type: text/plain

{"ticketId":"1","token":"96b29b22-cefb-4699-93b9-9fcc97aa003e","statut":"Resolu"}
###
### Send POST to have all tickets without techId
POST http://localhost:8080/genielog/ticket/list
Content-Type: text/plain

{"token":"96b29b22-cefb-4699-93b9-9fcc97aa003e"}
###
### Send POST to have all tickets with techId
POST http://localhost:8080/genielog/ticket/list
Content-Type: text/plain

{"token":"96b29b22-cefb-4699-93b9-9fcc97aa003e", "userId":7}
###