### Send POST to get init info for Ticket without id
POST http://localhost:8080/genielog/ticket/init
Accept: */*
Cache-Control: no-cache
Content-Type: text/plain

{"clientId":"2323233","token":"96b29b22-cefb-4699-93b9-9fcc97aa003e"}
###
### Send POST to get init info for Ticket with id
POST http://localhost:8080/genielog/ticket/init
Accept: */*
Cache-Control: no-cache
Content-Type: text/plain

{"clientId":"123456789","token":"96b29b22-cefb-4699-93b9-9fcc97aa003e", "ticketId":23}
###

### Send POST to create Ticket without task
POST http://localhost:8080/genielog/ticket/create
Content-Type: text/plain

{"token":"96b29b22-cefb-4699-93b9-9fcc97aa003e","ticket":{"adresse":{"codePostal":"69000","numero":32,"rue":"RUE ALAINE","ville":"LYON"},"categorie":"Etude","competences":[],"demandeur":{"id":12,"nom":"RENARD","prenom":"Maxime","sexe":"M"},"objet":"TESTEST","statut":"En cours","technicien":{"id":2,"nom":"VITTONE","prenom":"Jules","sexe":"M"},"type":"Demande","priorite":1}}
###
### Send POST to create Ticket with task
POST http://localhost:8080/genielog/ticket/create
Content-Type: text/plain

{"token":"96b29b22-cefb-4699-93b9-9fcc97aa003e","ticket":{"adresse":{"codePostal":"69000","numero":32,"rue":"RUE ALAINE","ville":"LYON"},"categorie":"Etude","competences":["Electricien"],"demandeur":{"id":1,"nom":"ALIMI","prenom":"Jean","sexe":"M"},"objet":"TESTEST","statut":"En cours","technicien":{"id":6,"nom":"SHEIKH MUHAMMAD","prenom":"Irteza","sexe":"M"},"type":"Demande","priorite":1,
"taches":[{"statut":"En cours", "objet":"TEST", "competences":[], "technicien":{"id":2,"nom":"VITTONE","prenom":"Jules","sexe":"M"}, "tempsEstime":40}]}}
###

### Send POST to modify Ticket without task
POST http://localhost:8080/genielog/ticket/modify
Content-Type: text/plain

{"clientId":123456789,"token":"96b29b22-cefb-4699-93b9-9fcc97aa003e","ticket":{"adresse":{"codePostal":"69000","numero":32,"rue":"RUE ALAINE","ville":"LYON"},"categorie":"Temperature","competences":["Electricien", "Frigoriste"],"demandeur":{"id": 12,"nom":"RENARD","prenom":"Maxime","sexe":"M"},"objet":"La vitrine réfrigérée n'est plus assez froide","description":"Bonjour,

 Notre meuble vitrine réfrigérée qui nous sert à la présentation des charcuteries n'est plus assez froid, il est impossible de descendre au-delà de 5°.
 ","statut":"Resolu","technicien":{"id":2,"nom":"Jules","prenom":"VITTONE","sexe":"M"},"type":"Incident","id":21,"priorite":2}}
###
### Send POST to modify Ticket with task
POST http://localhost:8080/genielog/ticket/modify
Content-Type: text/plain

{"clientId":123456789,"token":"96b29b22-cefb-4699-93b9-9fcc97aa003e","ticket":{"adresse":{"codePostal":"69000","numero":32,"rue":"RUE ALAINE","ville":"LYON"},"categorie":"Temperature","competences":["Electricien", "Frigoriste"],"demandeur":{"id": 12,"nom":"RENARD","prenom":"Maxime","sexe":"M"},"objet":"La vitrine réfrigérée n'est plus assez froide","description":"Bonjour,

 Notre meuble vitrine réfrigérée qui nous sert à la présentation des charcuteries n'est plus assez froid, il est impossible de descendre au-delà de 6°.
 ","statut":"En cours","technicien":{"id":2,"nom":"Jules","prenom":"VITTONE","sexe":"M"},"type":"Incident","id":20,"priorite":2,
 "taches":[{"statut":"Resolu", "objet":"TEST", "competences":["Electricien", "Informaticien"], "technicien":{"id":12,"nom":"TECHNOM","prenom":"TECHPRENOM","sexe":"M"}, "tempsEstime":50}]}}
###

##Send POST to modify the state
POST http://localhost:8080/genielog/ticket/state
Content-Type: text/plain

{"ticketId":"8","token":"96b29b22-cefb-4699-93b9-9fcc97aa003e","statut":"Resolu"}
###
### Send POST to have all tickets without techId
POST http://localhost:8080/genielog/ticket/list
Content-Type: text/plain

{"token":"96b29b22-cefb-4699-93b9-9fcc97aa003e"}
###
### Send POST to have all tickets with techId
POST http://localhost:8080/genielog/ticket/list
Content-Type: text/plain

{"token":"96b29b22-cefb-4699-93b9-9fcc97aa003e", "userId":8}
###