### Send POST to verify login
POST http://localhost:8080/GenieLogiciel_war_exploded/user/login
Content-Type: text/plain

{"userLogin":"1", "userPassword":"1234"}
###
### create User
POST http://localhost:8080/GenieLogiciel_war_exploded/user/create
Content-Type: text/plain

{"userLogin":"10", "userPassword":"1234"}
###