POST http://localhost:8080/GenieLogiciel_war_exploded/user/modify
Content-Type: text/plain

{
  "token": "96b29b22-cefb-4699-93b9-9fcc97aa003e",
  "staff": {
    "staffSexe": "M",
    "staffUserName": "1",
    "staffPassword": "",
    "staffMail": "philippe.claude@u-psud.fr",
    "staffAdress": {
      "numero": 12,
      "empty": false
      "rue": "avenue des champs",
      "ville": "PARIS",
      "codePostal": "75000"
    },
    "staffSurname": "Irteza",
    "staffName": "CLAUDE",
    "staffTel": "0612345678",
    "staffCompetency": [
      "Electricien"
    ],
    "staffRole": [
      "Admin"
    ],
    "staffId": 1
  }
}

###