### Send POST to verify login
POST http://localhost:8080/GenieLogiciel_war_exploded/user/login
Content-Type: text/plain

{"staffUserName":"1", "userPassword":"1234"}
###
### create User
POST http://localhost:8080/GenieLogiciel_war_exploded/user/create
Content-Type: text/plain

{"staffId":13,"staffUserName":"11","staffPassword":"1234","staffMail":"test@test.fr","staffAdress":{"numero":12,"rue":"avenue des champs","ville":"PARIS","codePostal":"75000"},"staffSurname":"Philippe","staffName":"CLAUDE","staffTel":"0504070105","staffCompetency":["Electricien","Frigoriste"],"staffRole":["Admin","RespTech"]}
###
### modify User mdp
POST http://localhost:8080/GenieLogiciel_war_exploded/user/modify
Content-Type: text/plain

{"staffUserName":"10", "userPassword":"4567","token":"96b29b22-cefb-4699-93b9-9fcc97aa003e"}
###